### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by Trapulo** [jdrouet/jolimail#263]
Hi, I tried to run the docker image as described in guide, but it fails:

ERROR: manifest for jdrouet/jolimail:master not found: manifest unknown: manifest unknown

any idea?
thanks

**Comment by jdrouet** [comment]
Yeah, `master` is not used anymore. If you go on [Docker Hub](https://hub.docker.com/r/jdrouet/jolimail/tags?page=1&ordering=last_updated), you can see that you can choose between `canary` (latest build from `main` branch) or `latest` (latest release).
So, in the `docker-compose.yml`, you can replace `master` by `canary` or `main` depending on what you want.

Also, if you don't run it on `amd64`, you've to use `main` because I don't build multi arch image for `canary` builds.

Hope that solves your issue, I'll fix the readme after work 😉

**Comment by Trapulo** [comment]
thank you now it works
